#!/bin/bash
myself="`readlink -f "$0"`"
mydir="`dirname "$myself"`"

#last_iovs=150
last_iovs=100
cycle=3600
#min_time=0
min_time=`date -d "2011-08-04 3:00 GMT" +%s`


export TNS_ADMIN=/afs/cern.ch/cms/DB/conddb/ADG
export LAS_LTAG=EcalLaserAPDPNRatios_last
#export LAS_DBCONNECT=oracle://cms_orcoff_prod/CMS_COND_311X_ECAL_LASP
#export LAS_DBCONNECT=oracle://cms_orcoff_prod/CMS_COND_42X_ECAL_LASP
export LAS_DBCONNECT=oracle://cms_orcon_adg/CMS_COND_42X_ECAL_LASP



trap "makeitnow=1" SIGHUP

while true; do
     /data1/ecalmon/auth
     t=`date +%s`
     "$mydir"/lasval_mkplots --last $last_iovs --tmin "$min_time" -d /afs/cern.ch/user/e/ecalmon/www/prompt
     makeitnow=0
     t1=`date +%s`
     dt=$((cycle+t-t1))
     echo "`date +'%F %R:%S'` sleeping $dt s... send a SIGHUP to wake me up..."
     while [ $dt -gt 0 -a $makeitnow != 1 ]; do
         sleep 10
         t1=`date +%s`
         dt=$((cycle+t-t1))
     done
done
